import { chromium } from "playwright-core";
import { channel } from "../browser.mjs";
/* Delete in the confirmation is press and hold. */
const hold = async (page, target, ms = 2300) => {
  const box = await target.boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.waitForTimeout(ms);
  await page.mouse.up();
};
const base = process.argv[2] ?? "http://localhost:3123";
const out = process.argv[3];
const mobile = process.argv[4] === "mobile";
const tag = mobile ? "m" : "d";
const b = await chromium.launch({ channel });
const ctx = await b.newContext({ viewport: mobile ? { width: 390, height: 844 } : { width: 1440, height: 900 }, permissions: ["clipboard-read", "clipboard-write"] });
const p = await ctx.newPage();
const errors = [];
p.on("pageerror", (e) => errors.push(e.message));
p.on("console", (m) => m.type() === "error" && errors.push(m.text()));
const log = (...a) => console.log(...a);
const shot = (n) => p.screenshot({ path: `${out}/${tag}-${n}.png`, fullPage: false });

await p.goto(base + "/dashboard/policies/474-981-34EDH20");
await p.waitForTimeout(900);
log("policy card:", (await p.getByRole("region", { name: "Claims", exact: true }).innerText()).replace(/\n/g, " | "));
await shot("0-policy");
await p.getByRole("link", { name: "Start a claim" }).click();
await p.waitForURL("**/claims/new");
await p.waitForTimeout(500);
await shot("1-type");
await p.getByRole("button", { name: /Cashless/ }).click();
await p.waitForTimeout(500);
log("step1 heading:", await p.locator("h1").innerText(), "| focused:", await p.evaluate(() => document.activeElement?.tagName));
await p.getByRole("button", { name: "Continue" }).click();
log("error:", await p.locator("p[role=alert]").innerText());
await p.getByLabel(/Kavya Raghavan/).check();
await shot("2-patient");
await p.getByRole("button", { name: "Continue" }).click();
await p.waitForTimeout(500);
log("step2:", await p.locator("h1").innerText());
await p.getByRole("button", { name: "Continue" }).click();
log("error:", await p.locator("p[role=alert]").innerText());
await p.getByLabel(/^Hospitalisation/).check();
await p.waitForTimeout(300);
log("treatment open:", await p.getByRole("button", { name: /What's the treatment called/ }).getAttribute("aria-expanded"));
await p.getByLabel("Treatment name").fill("Knee surgery");
await p.keyboard.press("Enter");
await p.waitForTimeout(300);
log("stage open:", await p.getByRole("button", { name: /Where are you in the treatment/ }).getAttribute("aria-expanded"));
await p.getByLabel(/^Planning a stay/).check();
await p.waitForTimeout(350);
await shot("3-treatment");
await p.getByRole("button", { name: "Continue" }).click();
await p.waitForTimeout(500);
log("step3:", await p.locator("h1").innerText());
await p.getByLabel(/Yes, I know the date/).check();
await p.getByLabel("Date of admission").fill("2026-09-01");
await p.getByRole("button", { name: "Continue" }).click();
log("past date error:", await p.locator("p[role=alert]").innerText());
await p.getByLabel("Date of admission").fill("2026-10-08");
await shot("4-dates");
await p.getByRole("button", { name: "Continue" }).click();
await p.waitForTimeout(500);
log("step4:", await p.locator("h1").innerText());
await p.getByLabel("Search hospitals").fill("velachery");
await p.waitForTimeout(200);
log("results:", await p.getByRole("status").first().innerText());
await p.getByLabel("Search hospitals").fill("");
await p.getByLabel(/Powai Lakeside/).check();
log("non-network note:", (await p.getByText(/isn't in Care Health's network/).count()) > 0);
// manual entry dialog
await p.getByRole("button", { name: /Can't find your hospital/ }).click();
await p.waitForTimeout(250);
log("dialog open:", await p.locator("dialog[open]").count());
await shot("5-dialog");
await p.keyboard.press("Escape");
await p.waitForTimeout(200);
log("dialog closed by Escape:", (await p.locator("dialog[open]").count()) === 0);
await p.getByLabel(/^Lakeview Hospital/).check();
await shot("6-hospital");
await p.getByRole("button", { name: "Send request" }).click();
for (const t of [350, 900, 1500, 2350, 2900]) {
  await p.waitForTimeout(t === 350 ? 350 : t - [350, 900, 1500, 2350, 2900][[350, 900, 1500, 2350, 2900].indexOf(t) - 1]);
  await p.screenshot({ path: `${out}/${tag}-ticket-${t}.png` });
}
await p.waitForFunction(() => document.querySelector("h1")?.textContent === "Claim request sent", null, { timeout: 15000 });
log("ticket heading:", await p.locator("h1").innerText(), "| focus:", await p.evaluate(() => document.activeElement?.textContent));
await p.getByRole("button", { name: "View claim" }).click();
await p.waitForURL(/claims\/CL\d{4}/);
await p.waitForTimeout(600);
const url = p.url();
log("claim page:", new URL(url).pathname, "|", (await p.locator("h1").innerText()).replace(/\n/g, " "));
log("details:", (await p.getByRole("region", { name: "Claim details" }).innerText()).replace(/\n/g, " | "));
await shot("7-claim");
await p.getByRole("button", { name: "Copy" }).click();
log("copied:", await p.evaluate(() => navigator.clipboard.readText()));
// list
await p.getByRole("navigation", { name: "Breadcrumb" }).getByRole("link", { name: "Claims", exact: true }).click();
await p.waitForURL(/\/claims$/);
await p.getByRole("region", { name: "Active claims" }).getByRole("link").first().waitFor();
log("list rows:", await p.getByRole("region", { name: "Active claims" }).getByRole("link").count());
await shot("8-list");
await p.goto(url.replace("?created=1", ""));
await p.waitForTimeout(600);
await p.getByRole("button", { name: "Delete claim" }).click();
await p.waitForTimeout(250);
log("delete dialog focus:", await p.evaluate(() => document.activeElement?.textContent));
await shot("9-delete");
await hold(p, p.getByRole("dialog").getByRole("button", { name: "Delete claim" }));
await p.waitForURL(/deleted=/);
await p.waitForTimeout(500);
log("after delete:", (await p.getByRole("status").first().innerText()), "| empty:", await p.getByText("No open claims").count());
await shot("10-empty");
await p.getByRole("navigation", { name: "Breadcrumb" }).getByRole("link", { name: "Care health NCB Super Premium with UAR" }).click();
await p.waitForTimeout(700);
log("policy card after:", (await p.getByRole("region", { name: "Claims", exact: true }).innerText()).replace(/\n/g, " | "));
log("errors:", errors.length ? errors : "none");
await b.close();
