import { chromium } from "playwright-core";
const base = process.argv[2] ?? "http://localhost:3123";
const b = await chromium.launch({ channel: "chrome" });
const errors = [];
const p = await (await b.newContext({ viewport: { width: 1586, height: 1030 }, deviceScaleFactor: 2 })).newPage();
p.on("pageerror", (e) => errors.push(e.message)); p.on("console", (m) => m.type() === "error" && errors.push(m.text()));
await p.goto(base + "/dashboard/policies/474-981-34EDH20"); await p.waitForTimeout(1500);
await p.getByRole("button", { name: /Which kind of claim/ }).click(); await p.waitForTimeout(2200);
const d = p.getByRole("dialog");
console.log("policy page opens with:", (await d.getByRole("log").innerText()).replace(/\n+/g, " | "));
console.log("answers:", (await d.getByRole("group", { name: "Your answer" }).innerText()).replace(/\n+/g, " | "));
await p.screenshot({ path: "out-bc/policyq.png" });
await d.getByRole("button", { name: "It's planned" }).click(); await p.waitForTimeout(1800);
console.log("next:", (await d.getByRole("log").innerText()).split("\n").slice(-3).join(" | "));
await p.keyboard.press("Escape"); await p.waitForTimeout(600);
await p.goto(base + "/dashboard/policies/474-981-34EDH20/claims"); await p.waitForTimeout(1500);
await p.getByRole("button", { name: /^Make a claim/ }).click(); await p.waitForTimeout(2200);
console.log("claims page opens with:", (await p.getByRole("dialog").getByRole("log").innerText()).split("\n").slice(0, 3).join(" | "));
await p.keyboard.press("Escape"); await p.waitForTimeout(600);
await p.goto(base + "/dashboard"); await p.waitForTimeout(1500);
await p.getByRole("button", { name: "Ask Ditto Buddy" }).click(); await p.waitForTimeout(2000);
await p.getByRole("dialog").getByRole("button", { name: "Make a claim" }).click(); await p.waitForTimeout(1800);
console.log("Buddy still asks:", (await p.getByRole("dialog").getByRole("log").innerText()).includes("Which policy is it for?"));
console.log("errors:", errors.length ? errors : "none");
await b.close();
