import { chromium } from "playwright-core";
import { channel } from "../browser.mjs";
const base = process.argv[2] ?? "http://localhost:3123";
const out = process.argv[3];
const S = process.argv[4];
const tag = process.argv[5] === "mobile" ? "m" : "d";
const b = await chromium.launch({ channel });
const p = await b.newPage({ viewport: tag === "m" ? { width: 390, height: 844 } : { width: 1440, height: 900 }, deviceScaleFactor: 1.5 });
const errors = [];
p.on("pageerror", (e) => errors.push(e.message));
p.on("console", (m) => m.type() === "error" && errors.push(m.text()));
const log = (...a) => console.log(...a);
const err = () => p.locator("p[role=alert]").innerText();
const next = async () => { await p.getByRole("button", { name: /^(Continue|Send claim)$/ }).evaluate((n) => n.click()); await p.waitForTimeout(450); };
await p.goto(base + "/dashboard/policies/474-981-34EDH20/claims/new"); await p.waitForTimeout(1000);
await p.getByRole("button", { name: /Reimbursement/ }).click(); await p.waitForTimeout(500);
log("step1:", await p.locator("h1").innerText());
await next(); log("err:", await err());
await p.getByLabel(/^Hospitalisation/).check();
await p.screenshot({ path: `${out}/${tag}-1.png` });
await next(); log("step2:", await p.locator("h1").innerText());
await next(); log("err:", await err(), "| focused:", await p.evaluate(() => document.activeElement?.id));
await p.locator("#r-patient").selectOption({ label: "Kavya Raghavan (Wife)" });
await p.locator("#r-amount").fill("60000000");
await next(); log("err:", await err());
await p.locator("#r-amount").fill("52500"); log("amount shows:", await p.locator("#r-amount").inputValue());
await p.locator("#r-reason").fill("Appendix surgery");
await p.locator("#r-hospital").fill("Lakeview Hospital");
await p.locator("#r-admission").fill("2027-01-10");
await next(); log("err:", await err());
await p.locator("#r-admission").fill("2026-09-28");
await p.locator("#r-discharge").fill("2026-09-25");
await next(); log("err:", await err());
await p.locator("#r-discharge").fill("2026-10-01");
await p.screenshot({ path: `${out}/${tag}-2.png`, fullPage: true });
await next(); log("step3:", await p.locator("h1").innerText(), "| preselected:", await p.getByRole("radio").isChecked());
await next(); log("step4:", await p.locator("h1").innerText());
await next(); log("err:", await err());
await p.locator("#r-doc-bills").setInputFiles([`${S}/bill1.pdf`, `${S}/bill2.pdf`]);
await next(); log("err:", await err());
await p.locator("#r-doc-discharge").setInputFiles(`${S}/discharge.pdf`);
await p.getByRole("button", { name: "Remove bill2.pdf" }).click();
log("bills now:", await p.getByText(/files? added/).first().innerText());
await p.screenshot({ path: `${out}/${tag}-4.png`, fullPage: true });
await next(); log("step5:", await p.locator("h1").innerText());
await p.screenshot({ path: `${out}/${tag}-5.png`, fullPage: true });
await next(); log("err:", await err());
await p.getByRole("button", { name: "Edit treatment" }).click(); await p.waitForTimeout(450);
log("edit jumps to:", await p.locator("h1").innerText(), "| amount kept:", await p.locator("#r-amount").inputValue());
await next(); await next(); await next();
await p.locator("#r-confirm").check();
await next();
await p.waitForTimeout(4800);
log("ticket:", await p.locator("h1").innerText(), "|", (await p.locator(".ticket-paper").innerText()).replace(/\s+/g, " ").slice(0, 260));
await p.screenshot({ path: `${out}/${tag}-ticket.png` });
await p.getByRole("button", { name: "View claim" }).click();
await p.waitForURL(/claims\/CL\d{4}/); await p.waitForTimeout(900);
log("claim page:", await p.locator("h1").innerText(), "|", (await p.getByRole("region", { name: "Claim details" }).innerText()).replace(/\s+/g, " "));
await p.screenshot({ path: `${out}/${tag}-claim.png`, fullPage: true });
await p.getByRole("navigation", { name: "Breadcrumb" }).getByRole("link", { name: "Claims", exact: true }).click(); await p.waitForURL(/\/claims$/);
await p.getByRole("region", { name: "Active claims" }).getByRole("link").first().waitFor();
log("list row:", (await p.getByRole("region", { name: "Active claims" }).getByRole("link").first().innerText()).replace(/\s+/g, " "));
await p.evaluate(() => localStorage.removeItem("ditto.claims.v1"));
// buddy
await p.goto(base + "/dashboard"); await p.waitForTimeout(1200);
await p.getByRole("button", { name: "Ask Ditto Buddy" }).click(); await p.waitForTimeout(1400);
const sheet = p.getByRole("dialog", { name: "Ditto Buddy" });
log("buddy greeting:", (await sheet.getByRole("log").innerText()).replace(/\s+/g, " "));
await sheet.getByLabel("Ask Ditto Buddy").fill("is room rent covered?"); await p.keyboard.press("Enter"); await p.waitForTimeout(1300);
log("buddy answer:", (await sheet.getByRole("log").innerText()).replace(/\s+/g, " ").slice(-120));
await sheet.getByLabel("Ask Ditto Buddy").fill("what's the weather"); await p.keyboard.press("Enter"); await p.waitForTimeout(1300);
log("buddy unsure:", (await sheet.getByRole("log").innerText()).replace(/\s+/g, " ").slice(-150));
await p.screenshot({ path: `${out}/${tag}-buddy.png` });
await p.keyboard.press("Escape"); await p.waitForTimeout(500);
await p.screenshot({ path: `${out}/${tag}-home.png` });
// quick actions
await p.goto(base + "/dashboard/policies/474-981-34EDH20"); await p.waitForTimeout(1200);
for (const name of ["Network hospitals", "Excluded hospitals", "FAQs"]) {
  await p.getByRole("button", { name: new RegExp("^" + name) }).click(); await p.waitForTimeout(1100);
  const d = p.getByRole("dialog", { name });
  log("sheet", name, "| items:", await d.locator("li, details, article").count());
  if (name === "FAQs") { await d.locator("summary").first().click(); log("faq opens:", await d.locator("details[open]").count()); }
  if (name === "Network hospitals") { await d.getByLabel("Search hospitals").fill("bengaluru"); await p.waitForTimeout(200); log("filtered:", await d.getByRole("status").innerText()); }
  await p.screenshot({ path: `${out}/${tag}-qa-${name.split(" ")[0].toLowerCase()}.png` });
  await p.keyboard.press("Escape"); await p.waitForTimeout(600);
}
log("errors:", errors.length ? errors : "none");
await b.close();
